spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/lebrb?user=lebrb&password=piotr}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://lebrb:piotr@localhost:27017/lebrb}
  redis:
    url: ${REDIS_URL:redis://127.0.0.1:6379}

jwt:
  secret: ${JWT_SECRET:secret}
  expiration: ${JWT_EXPIRATION:30}

words-counter:
  url: ${WORDSCOUNTER_URL:http://localhost:8081/words-counter}
