spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/lebrb?user=lebrb&password=piotr}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://lebrb:piotr@localhost:27017/lebrb}

jwt:
  secret: ${JWT_SECRET:secret}
  expiration: ${JWT_EXPIRATION:30}

words-counter:
  url: ${WORDSCOUNTER_URL:http://localhost:8081/words-counter}
